config/routes.rb
Pivotspec::Application.routes.draw do

  root :to => 'menu#start'  

  match 'started' => 'menu#started'
  match 'carspecs/createAxises' => 'carspecs#createAxises'

  resources :carspecs

end

app/models/carspec.rb
class Carspec < ActiveRecord::Base
  attr_accessible :specname, :spectype
  
  def to_s
    spectype + ':' + specname
  end
  
end

app/models/spec.rb
class Spec < ActiveRecord::Base
  attr_accessible :specname, :spectype
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/specs_controller.rb
class SpecsController < ApplicationController
  # GET /specs
  # GET /specs.json
  def index
    @specs = Spec.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specs }
    end
  end

  # GET /specs/1
  # GET /specs/1.json
  def show
    @spec = Spec.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spec }
    end
  end

  # GET /specs/new
  # GET /specs/new.json
  def new
    @spec = Spec.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spec }
    end
  end

  # GET /specs/1/edit
  def edit
    @spec = Spec.find(params[:id])
  end

  # POST /specs
  # POST /specs.json
  def create
    @spec = Spec.new(params[:spec])

    respond_to do |format|
      if @spec.save
        format.html { redirect_to @spec, notice: 'Spec was successfully created.' }
        format.json { render json: @spec, status: :created, location: @spec }
      else
        format.html { render action: "new" }
        format.json { render json: @spec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specs/1
  # PUT /specs/1.json
  def update
    @spec = Spec.find(params[:id])

    respond_to do |format|
      if @spec.update_attributes(params[:spec])
        format.html { redirect_to @spec, notice: 'Spec was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specs/1
  # DELETE /specs/1.json
  def destroy
    @spec = Spec.find(params[:id])
    @spec.destroy

    respond_to do |format|
      format.html { redirect_to specs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carspecs_helper.rb
module CarspecsHelper
end

app/helpers/specs_helper.rb
module SpecsHelper
end

app/views/carspecs/_form.html.erb
<%= form_for(@carspec) do |f| %>
  <% if @carspec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carspec.errors.count, "error") %> prohibited this carspec from being saved:</h2>

      <ul>
      <% @carspec.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spectype %><br />
    <%= f.text_field :spectype %>
  </div>
  <div class="field">
    <%= f.label :specname %><br />
    <%= f.text_field :specname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carspecs/edit.html.erb
<h1>Editing carspec</h1>

<%= render 'form' %>

<%= link_to 'Show', @carspec %> |
<%= link_to 'Back', carspecs_path %>

app/views/carspecs/index.html.erb
<h1>Listing carspecs</h1>

<table>
  <tr>
    <th>Spectype</th>
    <th>Specname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carspecs.each do |carspec| %>
  <tr>
    <td><%= carspec.spectype %></td>
    <td><%= carspec.specname %></td>
    <td><%= link_to 'Show', carspec %></td>
    <td><%= link_to 'Edit', edit_carspec_path(carspec) %></td>
    <td><%= link_to 'Destroy', carspec, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Carspec', new_carspec_path %>

app/views/carspecs/new.html.erb
<h1>New carspec</h1>

<%= render 'form' %>

<%= link_to 'Back', carspecs_path %>

app/views/carspecs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Spectype:</b>
  <%= @carspec.spectype %>
</p>

<p>
  <b>Specname:</b>
  <%= @carspec.specname %>
</p>


<%= link_to 'Edit', edit_carspec_path(@carspec) %> |
<%= link_to 'Back', carspecs_path %>

app/views/carspecs/showtree.html.erb
<h1>Tree View</h1>

<table border="1">
  <% @cube.getAxises.each do | name, values | %>
    <tr>
      <td><%= name %></td>
      <% values.each do | value | %>
        <td><%= value %></td>
      <% end %>
    </tr> 
  <% end %>
</table>
<br>

<table border="1">
  <tr>
  <% @cube.getRootNode().getAllChildren().each do | aNode | %>
    <td rowspan="<%= aNode.numberOfLeaf( 0 ) %>" valign="top" width="80" > <%= aNode.getValue %></td>
    <%= '</tr><tr>'.html_safe if aNode.endOfRow? %>
  <% end %>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pivotspec</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menu/start.html.erb
<h1>Pivot Spec デモ</h1>
<form action="started" method="get">
<br>
開始します。スタートボタンをクリックしてください。
<br>
<br>
<input name="start" type="submit" value="Start">
<br>
</form>
</body>

app/views/specs/_form.html.erb
<%= form_for(@spec) do |f| %>
  <% if @spec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spec.errors.count, "error") %> prohibited this spec from being saved:</h2>

      <ul>
      <% @spec.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spectype %><br />
    <%= f.text_field :spectype %>
  </div>
  <div class="field">
    <%= f.label :specname %><br />
    <%= f.text_field :specname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specs/edit.html.erb
<h1>Editing spec</h1>

<%= render 'form' %>

<%= link_to 'Show', @spec %> |
<%= link_to 'Back', specs_path %>

app/views/specs/index.html.erb
<h1>Listing specs</h1>

<table>
  <tr>
    <th>Spectype</th>
    <th>Specname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specs.each do |spec| %>
  <tr>
    <td><%= spec.spectype %></td>
    <td><%= spec.specname %></td>
    <td><%= link_to 'Show', spec %></td>
    <td><%= link_to 'Edit', edit_spec_path(spec) %></td>
    <td><%= link_to 'Destroy', spec, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spec', new_spec_path %>

app/views/specs/new.html.erb
<h1>New spec</h1>

<%= render 'form' %>

<%= link_to 'Back', specs_path %>

app/views/specs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Spectype:</b>
  <%= @spec.spectype %>
</p>

<p>
  <b>Specname:</b>
  <%= @spec.specname %>
</p>


<%= link_to 'Edit', edit_spec_path(@spec) %> |
<%= link_to 'Back', specs_path %>